### ISSUE TITLE
Songs in remote playlists do not respect playlist order.

### ISSUE THREAD

**Issue by Porco-Rosso** [NattyNarwhal/Submariner#116]
Hi, I've noticed that when streaming from Navidrome to Submariner, the songs inside playlists are in a seemingly random order.
Since track order are an important part of playlists, I'm hoping song order can be implemented.
PS: thanks for fixing the playlist sidebar order!

**Comment by NattyNarwhal** [comment]
This seems to be because:

* The playlist controller sorts by the track property `playlistIndex`
* ...but this never gets set for server playlists
* ...so Core Data just fetches in whatever order
* ...and that being a property of a track doesn't make sense, because tracks can belong to multiple playlists (unless we treat track order as volatile and reset it every time we load a new playlist)
* ...and an ordered set in Core Data is expensive and might not really get us what we want 

I think I see how to fix this ideally (make playlist item a many to many relationship between playlist and track, with ordering), but it'll be very annoying and requires another schema change.

**Comment by NattyNarwhal** [comment]
If we do treat playlist indices as volatile, then it does actually come out to be pretty simple:

```diff
diff --git a/Submariner/SBSubsonicParsingOperation.m b/Submariner/SBSubsonicParsingOperation.m
index c876ede..5ea7bf1 100644
--- a/Submariner/SBSubsonicParsingOperation.m
+++ b/Submariner/SBSubsonicParsingOperation.m
@@ -503,6 +503,7 @@ NSString *SBSubsonicPodcastsUpdatedNotification         = @"SBSubsonicPodcastsUp
                     exists = YES;
                 }
             }
+            track.playlistIndex = [NSNumber numberWithInteger: playlistIndex++];
             
             if(!exists) {
                 [currentPlaylist addTracksObject:track];
@@ -512,6 +513,7 @@ NSString *SBSubsonicPodcastsUpdatedNotification         = @"SBSubsonicPodcastsUp
         } else {
             // create it
             track = [self createTrackWithAttribute:attributeDict];
+            track.playlistIndex = [NSNumber numberWithInteger: playlistIndex++];
             [currentPlaylist addTracksObject:track];
             [track setServer:server];
             [track setPlaylist:currentPlaylist];
```

...though persisting the changes is another problem - I think just call `createPlaylist` with the full body (since `updatePlaylist` only does adds/deletes, not reordering).

Seems to work otherwise though. You may need to reload the playlist for it to correct when the change is made though.
